name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout repozytorium
    - name: Checkout code
      uses: actions/checkout@v3

    # Ustawienie wersji Pythona
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    # Instalacja zależności
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Testowanie aplikacji (jeśli są testy)
    - name: Run tests
      run: |
        echo "No tests defined yet!" # Możesz dodać unittest, pytest itd.

    # Budowanie obrazu Dockera
    - name: Build Docker image
      run: |
        docker build -t flask-hello-world .
